### ISSUE TITLE
Plugins not showing in DAW

### ISSUE THREAD

**Issue by FoxDawg** [mikeoliphant/AudioPlugSharp#12]
Hi @mikeoliphant,
I am trying to get a grip on the example plugins but have not yet succeeded on getting them to show up in Reaper or Ableton. I copy pasted the examples and moved the resulting binaries and jsons to my VST folder.
Is there anything that needs to be done for them to show in my DAW? Or is there any other way to "host" them to see that the plugin is working properly?

Cheers,

**Comment by mikeoliphant** [comment]
Hmmm, if you are just trying to deploy one of the examples unmodified, I'm not sure what the problem might be.

If the plugin isn't showing up in your DAW, that usually means that it crashed when the DAW was scanning it.

Have a look in "C:\Users\*your-user*\AppData\Roaming\AudioPlugSharp" and see if there are any log files there.

**Comment by FoxDawg** [comment]
Nothing there... I am currently building in VS2022, x64/Debug, but I'd be irritated if VS version was an issue.
Would you mind providing me the binary output of the SimpleExample from your machine? I'd like to pinpoint the problem here..

**Comment by mikeoliphant** [comment]
I'm using VS2022 now, so that shouldn't be a problem.

Here is a built version of SimpleExample:

https://drive.google.com/file/d/1BARbVr0LlrdaYU4Dq-Fjfjhdt8RXvlOg/view?usp=sharing

Note that this was built using .NET 6.0, while the current version on GitHub is targeting .NET 5.0 (which also works for me - I've just since switched to 6.0).

**Comment by mikeoliphant** [comment]
I just updated the GitHub version to .NET 6.0, so it is exactly what I used to build the binary.

**Comment by FoxDawg** [comment]
Thanks!
This is maximum weird 🤦‍♂️ Copying your binaries into my VST folder did work immediately. Then sequentially replacing each of _my_ files with yours, until none of mine were left, did _not_. Using your binaries in my own sln, upgrading to net6 and doing a clean build then worked again, and I even saw changes I did to the meta data of the plugin.
Could not manage to see the WPF example in Ableton yet, so that's a problem for tomorrow. Still don't see the underlying issue, but the symptom might be "solved" for now...

**Comment by mikeoliphant** [comment]
Ok, I think I know what is probably happening. Windows security can be picky about letting dlls load, and will sometimes block them. If you right-click on a dll, you can see if Windows is blocking it, and you can un-block it.

**Comment by FoxDawg** [comment]
You might have a point here. Moving the plugin folder to a less restricted path, say, %programdata%, might be worth a try.

**Comment by FoxDawg** [comment]
When trying to make the WPF example work as well, I saw that the wpf.runtime.config is not yet updated to net6. We can probably close my issue with this fix.

**Comment by mikeoliphant** [comment]
Good catch - I've committed a fix.
