### ISSUE TITLE
Parameter changes not propagated back to DAW UI

### ISSUE THREAD

**Issue by FoxDawg** [mikeoliphant/AudioPlugSharp#13]
Hi Mike,

when implement my own plugin I noted an issue concerning parameter settings that can also be reproduced with the WPF sample:
Ableton has a built-in view of the registered parameters of any plugin.
- When turning a knob in the Ableton view, the respective control also changes its value in the WPF plugin (right screenshot)
- When turning the dial in the WPF sample, the corresponding Ableton button does not receive the update and stays where it was (left screenshot).

The actual processing takes place with the correct value anyway, so this is maybe just a matter of PropertyChange somewhere.
I checked a few commercial plugins which seem to get it right.

![grafik](https://user-images.githubusercontent.com/64035807/159231464-d4cf7bf8-62cc-4845-8830-af7801126231.png)

Let me know if you need any further assistance there and thanks in advance,

Dennis

**Comment by mikeoliphant** [comment]
I haven't yet implemented the VST3 API calls to report parameter changes to the DAW. I just had a quick look at it, and it seems like it may take some thought to get it right.

**Comment by mikeoliphant** [comment]
This is now fixed.
