### ISSUE TITLE
Unable to compile example projects on VS2022 on Windows 11 machine

### ISSUE THREAD

**Issue by jgs731** [mikeoliphant/AudioPlugSharp#14]
Hello, I've been struggling to build the example projects from the repo on VS2022 (I ran all of the other steps in VS2019 to get CMake commands working) but I keep getting errors for both projects (I've attached log files for  SimpleExample/WPFExample to this issue ticket). 

I am running this on a Windows 11 machine, and I wondered if this may cause an issue with building this project?

If you need any more details I'll be able to provide those

[SimpleExample errors.txt](https://github.com/mikeoliphant/AudioPlugSharp/files/9087348/SimpleExample.errors.txt)
[WPFExample errors.txt](https://github.com/mikeoliphant/AudioPlugSharp/files/9087349/WPFExample.errors.txt)

**Comment by mikeoliphant** [comment]
From the errors, it looks like maybe you haven't built the VST sdk?

See the instructions at the bottom of the readme: https://github.com/mikeoliphant/AudioPlugSharp/blob/master/README.md

**Comment by jgs731** [comment]
Thanks for your response @mikeoliphant . 
So I ran the commands in the README and things seem to have completed successfully, however I now get a load of errors and I don't understand why these are occurring when running a release build (attached error log)
[build steinberg errors.txt](https://github.com/mikeoliphant/AudioPlugSharp/files/9087726/build.steinberg.errors.txt)

Do these errors indicate anything in particular?

**Comment by mikeoliphant** [comment]
try doing:

cmake.exe -G "Visual Studio 17 2022" -A x64 ../vst3sdk

instead

**Comment by jgs731** [comment]
Yeah that seemed to run and then subsequently build successfully. Thanks!
