### ISSUE TITLE
GetPluginFactory not exported

### ISSUE THREAD

**Issue by bradisbell** [mikeoliphant/AudioPlugSharp#15]
Hello!  I've had no trouble compiling your repo and using the example VSTs.  However, when trying to make my own, using SimpleExample as a guide, I'm unable to get my compiled VST to load.  If I try to load it in VSTHost, nothing happens.  I tried the VST3 SDK validator and received this error:

```
.\validator.exe MyVst.dll
* Loading module...

        MyVst.dll

Invalid Module!
The dll does not export the required 'GetPluginFactory' function
```

My project does contain a reference to AudioPlugSharp.dll.  I've also tried simply adding AudioPlugSharp to the solution and then adding a project reference.  Same result.

I followed your instructions on the README... my output directory does contain the bridge, runtimeconfig, deps.json, and Ijwhost.dll.

Any other place I should be looking for how to resolve this?  I'm guessing something is wrong with my build config, but I'm at a loss for where to check.  Thanks!

**Comment by mikeoliphant** [comment]
The dll that actually acts as the plugin from the perspective of the host is the bridge dll, so if you are loading the plugin from a file directly in a host, you should be loading "MyVstBridge.vst3".

**Comment by bradisbell** [comment]
That solves it!  Thank you!

**Comment by mikeoliphant** [comment]
Great!
