### ISSUE TITLE
WPFExample not able to load in Ableton

### ISSUE THREAD

**Issue by masschel** [mikeoliphant/AudioPlugSharp#16]
Hello, I can succesfully build the complete VS solution, and Ableton is able to detect all three plugins. The Midi and Simple Gain plugins can be added to a track and are functional. The WPF example fails, with Ableton reporting:

![image](https://user-images.githubusercontent.com/5830663/192878710-5c7e0200-6a86-407e-9266-367c7af1e298.png)

(Failed to create the VST3 plug-in "WPF Example Plugin". The VST3 plug-in could not be found) in case the image doesn't show.

Am I missing something?

Bart

**Comment by masschel** [comment]
Just to state the obvious, the message says VST3 plugin could not be found, but it is actually detected. Drag/drop in a track gives the above message, whereas for the other two plugin, this works like a charm.

![image](https://user-images.githubusercontent.com/5830663/192880187-860c2072-7d13-4ce9-abbc-c80fd0c2d3bd.png)

**Comment by masschel** [comment]
Just tried loading them in Fruity Loops, and it also seems to fail:

![image](https://user-images.githubusercontent.com/5830663/192885681-0b680e81-5a73-4aa0-9e36-1ada39046b6c.png)

I'm very very new to FL Studio, so it could be lack of experience on this one. I will create my own WPF based plug-in, and see if I can find sth on the way.

**Comment by mikeoliphant** [comment]
Strange. I just tested the WPF Example plugin in Reaper, and it worked fine.

Log files are written to "%appdata%/AudioPlugSharp" - you may want to look there.

**Comment by masschel** [comment]
Aha. Success. I had the repo cloned on my OneDrive, which iirc sometimes gives permission issues. I did a fresh clone and build in my development folder, and now it works:

![image](https://user-images.githubusercontent.com/5830663/192890651-ced2ea3d-22e5-45fd-bacf-5a5df21e7eb6.png)

The knobs do not change the sound, but I read in another issue that it's meant to work only for mono audio?

Me happy, let's do great things ;-). Thanks for pointing to the log folder, will be useful in the future.

Minor bug, the Midi Example project lacks Project Dependencies on the VST (and WPF?) projects. It builds before the other ones, and cannot copy the required files in the post-build step.

**Comment by mikeoliphant** [comment]
Yes - it is mono in, stereo out. How that operates depends on the DAW and how you have the channels configured (in Reaper, for example, it will pass the left channel into a mono plugin by default).

I've added the projected dependencies to for the MidiExample plugin - thanks for the heads-up.
