### ISSUE TITLE
Advice on development flow

### ISSUE THREAD

**Issue by masschel** [mikeoliphant/AudioPlugSharp#19]
Hi,

I could use some advice on developing a VST. The problem is that when a DAW is open (I tried Reaper and Ableton), they block the VST folder, so new compilations are not allowed to be copied in there.

I tried creating three projects: 1 - the AudioPlugSharp interface 2 - the View that will populate the VST and 3 - the library that will generate content. 1 won't need much changes, 2 from time to time, 3 is where the work is going on. I was thinking to only compile 3 and move it to the folder, so 1 (and/or 2) would not block me from keeping the DAW open. But alas, this doesn't work.

Closing the DAW, creating a new song, then a track, selecting the VST etc for every change seems cumbersome. Are there more efficient approaches available?

Cheers, Bart

**Comment by mikeoliphant** [comment]
Hi Bart - I suggest saving a test project with the VST enabled on a track how you want it. Then you can just re-open the DAW by loading that project after you copy your VST. That's pretty quick with Reaper since it loads so fast.

**Comment by masschel** [comment]
Hey Mike, thanks for the tip. Not really ideal, but for sure a speed-up :-).
