### ISSUE TITLE
What would it take to integrate this into a Maui app on WinUI-3, and then extend it for ios and android?

### ISSUE THREAD

**Issue by ToolmakerSteve** [mikeoliphant/AudioPlugSharp#21]
Two parts to this question:

* Maui on Windows App SDK (WinUI-3).
  You mention C++ binding and WPF; adapting to Maui (but WIndows only at first) should be similar to what was done for WPF, AFAIK.

* Any suggestions for getting the C++ bindings working on iOS/Android. .Net Core code should "just work" on those platforms, once it works in Maui on Windows. But I don't know what would need to be done re C++ bindings.

**Comment by mikeoliphant** [comment]
Working with Maui should definitely be do-able - it should be pretty similar to the WPF implementation.

As for iOS/Android, that's more of a problem. The link with C++ is through C++/CLI, which is Windows-only. Right now, the C++ stuff is really just there for integrating with VST3 - and that isn't really a thing on mobile.

That said, it might be possible to support the mobile-specific audio plugin environments (like Audio Unit on iOS) via Xamarin or Maui.
