### ISSUE TITLE
Loading multiple plugins built with different versions of .net framework crashes the host.

### ISSUE THREAD

**Issue by Federerer** [mikeoliphant/AudioPlugSharp#23]
With current version of AudioPlugSharp you cannot load plugins build with different versions of .net framework at the same time, Ijwhost.dll - it will throw an exception as you can't load multiple .net versions from single process when using mixed mode assemblies. There are some other options like [hosting api](https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting?source=recommendations), but it's limited to calling a static method (like main 😉) and getting a result. From my testing setting `rollForward: LatestMajor` in **runtimeconfig.json** helps, but it's not ideal, as plugin gets whatever newest version user has installed and there might be some breaking changes between major versions, but I think that It's better than crashing a host every time 😁 I think that it should be possible by adding **runtimeconfig.template.json** to the project [link](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/).

**Comment by mikeoliphant** [comment]
Just ran into this one while trying to add .NET 7 support. "rollForward" does seem to be the best solution, if not ideal.

**Comment by mikeoliphant** [comment]
Ok, this seems to be working pretty well. Building AudioPlugSharp for .NET 6.0 and adding "rollForward" seems to allow mixing of .NET 6.0 and .NET 7.0 plugins in the same host.

Feel free to re-open if you see any issues.
