### ISSUE TITLE
Rebuild all leads to a missing .vst3 error

### ISSUE THREAD

**Issue by rlalance** [mikeoliphant/AudioPlugSharp#25]
![image](https://github.com/mikeoliphant/AudioPlugSharp/assets/1323032/e6f33eb0-a5a5-4191-8b01-5fb92d9ab5db)

**Comment by rlalance** [comment]
![image](https://github.com/mikeoliphant/AudioPlugSharp/assets/1323032/2f9e1d8d-b237-41f1-a0a8-785b37f5eb8f)

**Comment by rlalance** [comment]
![image](https://github.com/mikeoliphant/AudioPlugSharp/assets/1323032/c4d59c69-87c1-493f-8883-ef72371bee80)

**Comment by rlalance** [comment]
![image](https://github.com/mikeoliphant/AudioPlugSharp/assets/1323032/b4d2beef-d95d-4e01-a63e-7c47614e92ed)

**Comment by mikeoliphant** [comment]
This happens because of circular project dependencies. The AudioPlugSharp project nuget build depends on AudioPlugSharpVST, but AudioPlugSharpVST depends on AudioPlugSharp.

Not sure that there is a way around this other than putting the nuget in a separate project.

**Comment by rlalance** [comment]
Oh, interesting! Thank you Mike!

How do you get this to build locally?

**Comment by mikeoliphant** [comment]
Just build it a second time ("Build", not "Rebuild").

**Comment by rlalance** [comment]
Ummmm, still the same....
for both SimpleExample and WPFExample.

I'll keep digging.

**Comment by rlalance** [comment]
Actually, that VST3 file is not present on my machine at all.

![image](https://github.com/mikeoliphant/AudioPlugSharp/assets/1323032/c11a905a-9760-4238-bfa3-d0efa23df90e)


Where do I find that file?

**Comment by mikeoliphant** [comment]
That file is built by the "AudioPlugSharpVst" project - did it build successfully?

It should be in:

"AudioPlugSharp\x64\Release\AudioPlugSharpVst.vst3"

(or "\Debug\" for a debug build)

**Comment by rlalance** [comment]
yeah, weird. That project builds, but ends up with an error. So that means, it has a dependency on .vst3 files to build...

![image](https://github.com/mikeoliphant/AudioPlugSharp/assets/1323032/cc2fb07e-c19f-4ea9-a4c4-3a322abd3bb6)

**Comment by rlalance** [comment]
I'm going to close everything, `git clean -fdx`, and start over.

**Comment by rlalance** [comment]
@mikeoliphant Just out of curiosity, do you have time for a short contract to assist our Game Studio with this?

We so close to the finishing line here :D

**Comment by mikeoliphant** [comment]
Not looking for contract work right now - sorry.

Btw, if you are just looking to use AudioPlugSharp to build a plugin, it is a lot easier to just use the nuget packages:

https://www.nuget.org/packages?q=audioplugsharp

**Comment by rlalance** [comment]
np, thank you Mike.

I need to host dehuminazer II, from Krotos, but that darn plugin is a PITA to use. It's spitting out silence.

So, I'm looking for alternate host solution, better in C# too, because the rest of our tooling is Unity or .net 6.

**Comment by rlalance** [comment]
So, right now, i'm investigating hosting .dll based VST3 plugins.

**Comment by mikeoliphant** [comment]
If  you are looking to create a host, then unfortunately AudioPlugSharp won't help you - it is just for designing VST *plugins*.

**Comment by rlalance** [comment]
OHhhh! Darn... ok, thank you Mike!
