### ISSUE TITLE
VST3 WpfExample not recognized in Cubase

### ISSUE THREAD

**Issue by dansted** [mikeoliphant/AudioPlugSharp#26]
I've cloned the AudioPlugSharp repository, build the vstsdk.sln and AudioPlugSharp.sln, moved the files to a folder which Cubase scans for plugins. But my Cubase 12 Elements does not recognize WpfExample plugin as a VST3 plugin, it thinks it's a VST2 plugin and adds comment "Unsupported Architecture". Am I doing something wrong ? 

![unsupported](https://github.com/mikeoliphant/AudioPlugSharp/assets/31686436/b8896f38-b2f6-4a2f-8967-caac2a7b71fc)

**Comment by mikeoliphant** [comment]
Those dlls aren't the plugin. "WPFExampleBridge.vst3" is the plugin.

**Comment by dansted** [comment]
Cubase just ignores the "WPFExampleBridge.vst3.

**Comment by dansted** [comment]
I've also tried another VST3 host named Element by Kushview and then I get this error when scanning the vst.

![issue](https://github.com/mikeoliphant/AudioPlugSharp/assets/31686436/d99c977f-fb7d-4c2f-b6b4-3026f0bc0b59)

**Comment by mikeoliphant** [comment]
Not sure what the problem could be - I just tested in Element and it worked fine for me.

Try looking in the "AudioPlugSharp" folder in "%appdata%" and see if you have any log files with information in them.

**Comment by dansted** [comment]
I cant find any AudioPlugSharp folder in appdata.

![image](https://github.com/mikeoliphant/AudioPlugSharp/assets/31686436/5b595663-5256-4a6e-b18d-581ffe7a9983)

**Comment by mikeoliphant** [comment]
Then likely whatever went wrong happened before the plugin got a chance to log anything.

**Comment by mikeoliphant** [comment]
If you can zip up your binaries and put them somewhere I can grab them, I can test whether they run on my machine.

**Comment by mikeoliphant** [comment]
Closed due to inactivity.
