### ISSUE TITLE
Some Build Issues

### ISSUE THREAD

**Issue by MOAMaster** [mikeoliphant/AudioPlugSharp#5]
Very elegant wrapper classes to hide all the confusing VST plumbing and wiring.

AudioPlugSharpVst will not compile under VS 2022, Must use VS 2019
   This is an MS problem. They issued VS 2022 without upgrading the
     Apphost Pack and the Nuget package restore. 
    Compiling AudioPlugSharpVst leads to an error message. I found
    about 6 suggested fixes. None of them work. Stay away from VS 2022
    for these projects
    I don't think you can fix this issue. Only microsoft can.

Must run VS 2019 as administrator
    if you don't run as administrator, you get all sorts of set local host errors.
    These occur when trying to copy the bridge files in the post build step.
    Running as administrator lets them work correctly

current release has vstsdk as debug but AudioPlugSharp and others as release
for both vstsdk, AudioPlugSharp, change SOLUTION Active config to Realease/x64
    VS complains when vstsdk is debug but AudioPlugSharp is release.

in AudioPlugSharp, click on WPFExample to open .csproj
change root project to Microsoft.NET.sdk
    WPFExample has a problem with the root project as currently configured

you can fix the last two issues so that they are no longer a problem.

you might want to update your instructions to discuss the first two issues.

**Comment by mikeoliphant** [comment]
Visual Studio / Git doesn't seem to save the current build configuration, so it was defaulting to "Any CPU" instead of "x64". I have removed the non-x64 targets, so this won't cause confusion in the future.

The current setup builds without errors for me on VS2019 - tested with a fresh clone from github.

**Comment by MOAMaster** [comment]
Now I am getting the following error message:

 


Severity

Code

Description

Project

File

Line

Suppression State


Error

MSB8020

The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 build tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

AudioPlugSharpVst

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets

439

 

 

This built yesterday but now won’t build.

I didn’t download anything new from Github, but maybe VS downloads all on it own.

 

Did you compile this under the most recent VS 2019?

That is the one I downloaded.

 

2019 was updated multiple times.

 

Thanks.


Bruce

**Comment by mikeoliphant** [comment]
I am running the latest VS2019 (16.11.8). I'm not sure why it is giving you errors about Platform Toolset v143. I am building it using v142. I think v143 is for VS2022.

**Comment by MOAMaster** [comment]
That is possible. I have both on my machine.

I opened under VS 2019 but who knows.

 

Let me close all down, reopen, and see if the problem is fixed.

 

Will get back to you.


Thanks for the response.

 

Like I said, really elegant wrappers.

 

Bruce

**Comment by MOAMaster** [comment]
My apologies. Operator error on my part.

I have bronchitis, not thinking too clearly.

 

I opened VS 2019 as admin but somehow

I opened the solution I had attempted to build under VS 2022.

That caused the confusion.

 

I closed all down.

Then, I reopened VS 2019 as admin,

and opened the version I had built under VS2019.

That built just fine.

 

Again, my apologies, operator error.

 

Thanks for you patience.

 

Bruce

**Comment by MOAMaster** [comment]
I did a pull of the latest master and all built just fine.


Thanks again for your hard work on this.

 

Best Regards, Bruce

**Comment by mikeoliphant** [comment]
Glad it is working for you now!

**Comment by MOAMaster** [comment]
I filed a bug report with Microsoft for the failure to build under VS 2022.

Having problems with The Apphost pack is not installed and 

NuGet package restore is not supported seems like a major flaw

when a new product is issued.

 

I wasted two full days trying to find a workaround.

None of the suggested workarounds worked, even those

from Microsoft.

 

I have developed software since 1969. Yep I have been around 

a long time. Rule #1: don’t break anyone’s software that depends

on your product. When I was a consultant for MS some years ago,

we had arguments about this. They didn’t understand then, they

don’t seem to have learned.

 

Will let you know if they ever respond.

Their feedback system is pretty good, so hopefully

I will hear something.

**Comment by mikeoliphant** [comment]
VS2022 is still pretty new, so I'm guessing there is a bunch of stuff like this.

**Comment by MOAMaster** [comment]
Yep, that is the way they release products.

They have so many users worldwide that they know they can’t 

test for every environment and situation.

 

So, they let all of us debug the software.

But the problems I had seem like pretty big ones that

they should have planned for.

 

Oh, well, …

**Comment by MOAMaster** [comment]
Mike,

 

Sorry to bug you, but I am missing something.

I am trying to build a wpf plugin from scratch.

I tried class library, wpf class library, and winforms class library project templates.

None of these gives the same framework dependencies as your WPFExamplePlugin.

 

So, which project template do I need to use?

Thanks for your  help.


Bruce

**Comment by mikeoliphant** [comment]
You want to create a WPF application for .NET Core - not .NET Framework.

Mike

**Comment by MOAMaster** [comment]
An application not a class library?

 

Thank you.

Appreciate your help.


Bruce

**Comment by MOAMaster** [comment]
I finally created a new project.

Just went into File Explorer, copied the WPF Example,

changed the name of the folder, and the name of the csproj and cs files.

Added the project to AudioPlugSharp.

Then, updated the name space, the class, and the initializer method

and everything built and deployed just fine.

 

Never could future out project template that gave me the same libraries

as you had but the copy/paste/edit method worked just fine.

 

Thanks again for your help.


Bruce

**Comment by mikeoliphant** [comment]
My guess is that you were just missing references to the AudioPlugSharp and
AudioPlugSharpWPF dlls. Copying the existing project works, though.

**Comment by MOAMaster** [comment]
I could not find a template that included the windowsdesktop.app framework.

It used to be that you could add frameworks manually but they seem to have taken

that away as an improvement.

 

But copying the project worked, so I am OK.

 

Thanks again.


Best Regards, Bruce

**Comment by MOAMaster** [comment]
I hope you and your family are having a nice new years eve.

 

I see you created a slider class which you manage.

Nicely done.

 

I want to add some buttons to the Editor Window.

How would I do that?

 

For instance, I am creating a filter that keeps a history

of predictions and waveform values. I need to give

the user a button to reset the histories back to initial

values. I found stop and start but that won’t really do.

The user might stop in the middle change a parameter value

or look at something else, then start again. I would want

the history to remain intact if in the middle.

 

If buttons are not possible, how do I detect that we are at

the beginning of the waveform? Can’t just set a flag because

you still have to know when you are at the beginning of the

waveform to know when to reset the flag.

 

Any help will be appreciated.

Thanks.

 

Bruce

**Comment by MOAMaster** [comment]
Mike,

I have encountered a couple of issues.

 

1.	The default value appears to be ignored. I set the default value.

But, when the knob is displayed, the position is always 0.

 

2.	I set breakpoints to trace through InitializeProcessing.

This method was called twice when the plugin was loaded.

I had to do some programming to get around this.

 

I did change to stereo input so is it calling for each channel?

That doesn’t make sense.

 

3.	I deleted the plugin while playing.

When I reinstalled while playing, the knobs appear at their last value.

But, when a plugin is deleted, then reinstalled, it should reinitialize.

 

4.	There is a method to get the value but not one to set the value of a parameter.

Can we have a method that sets the value and updated the corresponding knob position?

 

Am kind of stuck without some solutions here.

 

Thanks.

Bruce Krell

**Comment by MOAMaster** [comment]
Mike,

 

I desperately need your help.

My default values don’t take.

I finally figured out why.

 

Your WPF Example has two parameters – both have a range that consists

of a negative value and a positive value.

 

My plugins have parameters that range from 0 or a small positive to a larger positive – no negative values.

 

I tested this and confirmed.

When I use a range from 0/small pos to larger positive, the defaults won’t take.

When I use a range from a negate to a positive, the defaults take.

 

I have spent several days trying to program around this issue,without any success.

I desperately need the range for a parameter to be from 0/small positive to a larger positive.

 

You are making an invalid assumption in your calculations.

Is it possible for you to fix this? 

Right now I can’t get my plugins to work because of this assumption.

 

I believe that the assumption might be in your calculations in class DialToAngleConverter, method Convert.

This is something you might be able to fix in minutes.


Can you please help?

 

thanks.


Bruce Krell

**Comment by MOAMaster** [comment]
MORE On Default Values

 

I did some more testing with your WPFSimpleExample.

 

WHen you set the range to be from negative to positive,

it looks like there are a few other hidden assumptions.

 

The negative and positive values have to “match”, ie, -100 to 100.

 

Regardless of what you set as the default value, the knob appears to always be in the middle.

 

I have searched in dial and AudioPluginParameter, and can’t seem to find the problem.

 

Any range of values should be accepted.

The dial should always be placed in it’s relative location between those values.


Appreciate any fixes.

 

Thanks.

Bruce

**Comment by mikeoliphant** [comment]
Bruce - you are responding on a github issue thread that is unrelated and
has been closed. In future, please open an issue specifically relating to
the problem you are having.

The default value was working for double-click behavior (the dials reset to
default value on double-click), but parameters were not being initialized
to the default value on startup. I have committed a fix for this.

I am unable to reproduce your other issues - Min/Max values are working as
expected for me for all ranges I've tried.

Mike

**Comment by MOAMaster** [comment]
Default Fixed:

 

In AudioPluginBase, I changed the method:

 

       public void AddParameter(AudioPluginParameter parameter)

        {

            parameter.Value = parameter.DefaultValue;

            parameterList.Add(parameter);

            parameterDict[parameter.ID] = parameter;

        }

 

I just added that first line.

That seems to force a refresh of the dial so that the dial position matches the default value.

 

You might want to do a bit of testing before you add that line.

 

Thanks.


Bruce

**Comment by MOAMaster** [comment]
Sorry, will submit a new issue in the future.

 

Thanks for responding.

 

Yes, the default value was working for double click but

not initialized on startup. I sent you one fix. I’ll check out

your fix which is likely better.

 

Sorry, further testing showed that the range worked ok, just

the default failed.

 

Thanks again.

 

Sorry to be such a pain.

I have 3 noise filter plugins going that I am getting to work.

 

Best Regards,


Bruce

**Comment by mikeoliphant** [comment]
The fix I committed is basically the same as what you did - it just needed
to set the default value when the parameter is created.
