### ISSUE TITLE
Upgraded WPFExample

### ISSUE THREAD

**Issue by MOAMaster** [mikeoliphant/AudioPlugSharp#6]
I updated your WPFExamplePlugin to work with stereo input.
I commented out the original mono instructions and inserted the stereo input code.
That way the programmer can see both.

Would be happy to contribute if you like.
Send me an e-mail at BKrell@SWArchitects.com
Will send to you.

Thanks again for all the work on this.

Bruce Krell

**Comment by mikeoliphant** [comment]
Thanks for the offer, but I think I'd rather keep the example as simple as possible.

**Comment by MOAMaster** [comment]
To handle stereo input adds 1 line of code and changes 4 others.

The example would still be very simple and realistic.

You would still have the mono input in your simple example.

Hardly anyone has to deal with mono files these days.

Most audio files are stereo.

 

With stereo inputs, you see the power and smoothness of the pan in the wpf example without really

adding any complexity since only 1 line of code is added. Because the left and right

channel are enough different.

 

Seems like a short sighted decision on your part.

 

Bruce
