### ISSUE TITLE
Looking For Advice

### ISSUE THREAD

**Issue by MOAMaster** [mikeoliphant/AudioPlugSharp#7]
Hi, Mike, Not sure this is an issue but I am seeing some strange behavior.
I wrote a plugin. The plugin creates a helper class to do the work. Inside the helper
class are some buffers used to store historical information.

When sound data enters the plugin, I check to see if parameters have changed. If so, I pass them to the helper class.
Then I pass the sound data to the helper class and the outputs are calculated.
The first plugin has 2 parameters. As I change the parameters, I can hear the output sound being updated.
So, the knob changes are correctly being fed to the helper class.

I then created two additional helper classes for two other plugins.
Plugin one has 4 parameters, plugin two has 5 parameters.
I am using the same approach.

One of these plugins doesn't produce any output sound.
The other plugin stops working after I change a few of the parameters.

I know the helper classes work perfectly.
All 3 are statistical algorithms.
I implemented them in matlab, then in C#.
The C# implementations are stress tested with a driver.
Furthermore, all 3 helper classes are used in a number of desktop applications
for the past 10 years.

The helper classes do maintain historical data so the buffers are redefined when
the parameters change. I tried making the helper class instances as static variables,
but that did not make any difference.

This is all pretty vague.

Any suggestions here?
Also, am wondering if the Plugins do some funny things with memory that is different from a desktop.
But, if so, why would the first plugin work correctly but the others mess up?

Thanks for any help/suggestions.

Bruce

**Comment by mikeoliphant** [comment]
This sounds like there issues specific to your plugins. The AudioPlugSharp interface is very simple - your plugin is in complete control of what happens to the audio stream and how it is affected by the parameters.

**Comment by MOAMaster** [comment]
What you say is very likely.

 

Was just wondering in you had seen any weirdness like this before?

 

No problem. Just close the issue since it’s not really an issue.

 

Thanks for responding.


Best Regards, Bruce

**Comment by mikeoliphant** [comment]
Best of luck with sorting it out.
